# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mark Palmer
tagline:          'A Jekyll theme'
description:      'Dedicated Aspiring Data Analyst. A highly adaptable, results-driven professional with over 10 years of experience in stock control, logistics, and team leadership. Proficient in IT systems including Microsoft Business Central (BC) and Sage. Adept at problem-solving, multitasking, and navigating fast-paced environments. Seeking a dynamic role in data analytics that offers new challenges and opportunities for professional growth. 
url:              https://www.linkedin.com/in/mark-palmer-9315b0329/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
